# Used to let travis know what language is being used
language: java
jdk:
- oraclejdk8
# Git strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
  - $HOME/.m2
  
script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)